array: src/array.h File Reference
array.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <time.h>
#include <assert.h>
Macros
#define ZERO 0
#define ONE 1
#define TWO 2
#define MAX_LENGTH 20
#define MAX_ELEMENT 15
#define NEW_LINE "\n"
#define INT "%d"
#define PRINT_MEAN "%sMedia degli elementi dell'array: %.2f"
#define SEPARATOR_LINE "-"
#define DOUBLE_STRING "%s%s"
#define GENERATED_ARRAY "Array generato: "
#define ORDERED_ARRAY "Array ordinato: "
Functions
void srand_time ()
int generate_length ()
int * generate_array (int length)
void print_array (char *message, int *array, int length)
float mean (int *array, int length)
void print_mean (int *array, int length)
bool ordered_array (int *array, int length)
void bubble_sort (int *array, int length)
int median (int *array, int length)
void print_median (int *array, int length)
int generate_number ()
void print_number (int number)
bool linear_search (int *array, int length, int number)
void print_search_result (int *array, int length, int number)
Macro Definition Documentation
#define DOUBLE_STRING "%s%s"
Definition at line 26 of file array.h.
Referenced by print_array().
#define GENERATED_ARRAY "Array generato: "
Definition at line 27 of file array.h.
#define INT "%d"
Definition at line 23 of file array.h.
Referenced by print_array().
#define MAX_ELEMENT 15
Definition at line 21 of file array.h.
Referenced by generate_number().
#define MAX_LENGTH 20
Definition at line 20 of file array.h.
Referenced by generate_length().
#define NEW_LINE "\n"
Definition at line 22 of file array.h.
Referenced by print_array(), print_mean(), print_median(), and print_search_result().
#define ONE 1
Definition at line 18 of file array.h.
Referenced by binary_search(), bubble_sort(), ordered_array(), and print_array().
#define ORDERED_ARRAY "Array ordinato: "
Definition at line 28 of file array.h.
#define PRINT_MEAN "%sMedia degli elementi dell'array: %.2f"
Definition at line 24 of file array.h.
#define SEPARATOR_LINE "-"
Definition at line 25 of file array.h.
Referenced by print_array().
#define TWO 2
Definition at line 19 of file array.h.
Referenced by binary_search(), and median().
#define ZERO 0
Definition at line 17 of file array.h.
Referenced by binary_search(), bubble_sort(), generate_array(), generate_length(), linear_search(), mean(), median(), ordered_array(), and print_array().
Function Documentation
void bubble_sort (int * array, int length)
Ordina in maniera crescente gli elementi dell'array di dimensione stabilita dal parametro length
Precondition
il parametro length deve essere un numero intero maggiore di 0
Postcondition
gli elementi dell'array sono ordinati in maniera crescente
Parameters
array
length
Definition at line 72 of file array.c.
References ONE, ordered_array(), and ZERO.
int* generate_array (int length)
Genera in modo casuale gli elementi dell'array di dimensione stabilita dal parametro length
Precondition
il parametro length deve essere un numero intero maggiore di 0
Returns
Definition at line 21 of file array.c.
References generate_number(), and ZERO.
int generate_length ()
Genera in modo casuale la dimensione dell'array
Postcondition
il numero generato deve essere maggiore di 0
Returns
Definition at line 14 of file array.c.
References MAX_LENGTH, and ZERO.
int generate_number ()
Genera in modo casuale il numero da cercare nell'array
Returns
Definition at line 103 of file array.c.
References MAX_ELEMENT.
Referenced by generate_array().
bool linear_search (int * array, int length, int number)
Effettua la ricerca lineare del parametro number nell'array di lunghezza stabilita dal parametro length
Precondition
il parametro length deve essere un numero intero maggiore di 0
Parameters
array
length
number
Returns
Definition at line 114 of file array.c.
References ZERO.
Referenced by print_search_result().
float mean (int * array, int length)
Restituisce la media degli elementi dell'array di dimensione stabilita dal parametro length
Precondition
il parametro length deve essere un numero intero maggiore di 0
Parameters
array
length
Returns
Definition at line 44 of file array.c.
References ZERO.
Referenced by print_mean().
int median (int * array, int length)
Restituisce l'elemento centrale dell'array ordinato di dimensione stabilita dal parametro length
Precondition
il parametro length deve essere un numero intero maggiore di 0
gli elementi dell'array devono essere ordinati in maniera crescente
Parameters
array
length
Returns
Definition at line 86 of file array.c.
References ordered_array(), TWO, and ZERO.
Referenced by print_median().
bool ordered_array (int * array, int length)
Verifica che in un array di dimensione stabilita dal parametro length gli elementi siano ordinati in maniera crescente
Precondition
il parametro dim deve essere un numero intero maggiore di 0
Parameters
array
length
Returns
Definition at line 60 of file array.c.
References ONE, and ZERO.
Referenced by binary_search(), bubble_sort(), and median().
void print_array (char * message, int * array, int length)
Stampa a video gli elementi dell'array di dimensione stabilita dal parametro length
Parameters
message
array
length
Definition at line 30 of file array.c.
References DOUBLE_STRING, INT, NEW_LINE, ONE, SEPARATOR_LINE, and ZERO.
void print_mean (int * array, int length)
Stampa a video la media degli elementi dell'array
Parameters
array
length
Definition at line 53 of file array.c.
References mean(), and NEW_LINE.
void print_median (int * array, int length)
Stampa a video l'elemento mediano dell'array ordinato
Parameters
array
length
Definition at line 92 of file array.c.
References median(), and NEW_LINE.
void print_number (int number)
Stampa a video il numero da cercare nell'array
Parameters
number
Definition at line 107 of file array.c.
void print_search_result (int * array, int length, int number)
Stampa a video il risultato della ricerca
Parameters
array
length
number
Definition at line 151 of file array.c.
References linear_search(), and NEW_LINE.
void srand_time ()
Assicura che ad ogni lancio il programma generi in modo casuale numeri sempre diversi
Definition at line 10 of file array.c.